### ISSUE TITLE
Remove Snowflake integration for New Relic

### ISSUE THREAD

**Issue by chuka2003** [newrelic/newrelic-snowflake-integration#13]
How do you advise we safely remove/disable the Snowflake integration for New Relic.

**Comment by matewilk** [comment]
I would suggest to do the following:
- stop New Relic Infra agent
- remove copied `flexConfigs/snowflake-{platform}` file from `/newrelic-infra/integrations.d/` directory
- remove `NEWRELIC_SNOWFLAKE_HOME` (and `NEWRELIC_SNOWFLAKE_CONFIG_PATH` if you had set it up) environment variable from your environment
- if you run the agent as a `systemd` service follow [this](https://github.com/newrelic/newrelic-snowflake-integration#when-the-agent-is-running-as-a-systemd-service) instruction in inverted order
- remove the `newrelic-snowflake-integration` directory which you created by cloning this repo
- restart New Relic Infra agent (if you want to use it - otherwise follow instructions from [here](https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/update-or-uninstall/uninstall-infrastructure-agent/) to uninstall the agent)
