### ISSUE TITLE
Snowflake credentials are visible in clear text in New Relic

### ISSUE THREAD

**Issue by notonb** [newrelic/newrelic-snowflake-integration#4]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Snowflake credentials are visible in clear text if the custom query fails for some reason. Anybody who has the ability to query NR can see the Snowflake's credentials.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

Any non working query can be used to reproduce.

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior
Strip out the password or mask it with "*****"

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment
Linux
[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by danifitz** [comment]
Thanks for raising this @notonb we will repro the issue and get back to you.

**Comment by danifitz** [comment]
Hey @notonb thanks again for raising this and apologies for this fix taking a while. Fixed in release `0.1.3` : https://github.com/newrelic/newrelic-snowflake-integration/releases/tag/v0.1.3

note: environment variables have been deprecated in favour of a .yaml file for config. This prevents the issue you reported. I will also be working on adding support for credential management solutions like Hashicorp Vault in the future.
